services:
  web:
    build: .
    image: beacon-ui:latest
    container_name: beacon-ui
    hostname: beacon-ui
    ports:
      - "8080:80"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      GENERATE_SOURCEMAP: "false"

      REACT_APP_BEACON_UI_OIDC_ENDPOINT: ${BEACON_UI_OIDC_ENDPOINT:-https://login.aai.lifescience-ri.eu/oidc/}
      REACT_APP_BEACON_UI_OIDC_CLIENT_ID: ${BEACON_UI_OIDC_CLIENT_ID:-d3132b30-3a07-4a66-a065-512674fac86e}
      REACT_APP_BEACON_UI_OIDC_REDIRECT_URI: ${BEACON_UI_OIDC_REDIRECT_URI:-https://beacons.bsc.es/}
      REACT_APP_BEACON_UI_OIDC_LOGOUT_REDIRECT_URI: ${BEACON_UI_OIDC_LOGOUT_REDIRECT_URI:-https://beacons.bsc.es/}
      REACT_APP_BEACON_UI_API_BASE_URL: beacon2-ri-api-main-beacon-omopcdm-alchemy-1:5050
      REACT_APP_BEACON_UI_PUBLIC_URL: ${BEACON_UI_PUBLIC_URL:-https://beacons.bsc.es/}
    volumes:
      - ./public/config:/usr/share/nginx/html/config:ro
    networks:
      - default
      - beacon-api-network

networks:
  beacon-api-network:
    external: true
    name: database_beacon-network